import "./globals.css";

export const metadata = {
  title: "Colmobil Club",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log({children})
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
